### PR TITLE
PP-8370: Enable nginx stream logging

### PR DESCRIPTION
**Pull request by jfharden**
# What

* Enable tcp stream logging
* Run nginx with exec so OS signals are correctly passed to the nginx process
* Add local testing configuration using docker-compose
* Update the README to explain how to use the local testing configuration

# Why

TCP Stream logging allows us to audit connections through the tcp-proxy.
The docker-compose local testing environment makes development cycles on the tcp-proxy much shorter.

# Running locally example

This shows a build and run locally
```
11:04 : GDS11088 : no_aws : (pp-8370-enable-nginx-stream-logging) : [~/gitdevel/github.com/alphagov/pay-tcp-proxy]
♥ $ docker-compose build
nginx-backend uses an image, skipping
Building pay-tcp-proxy
[+] Building 1.3s (15/15) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                       0.0s
 => => transferring dockerfile: 37B                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                          0.0s
 => => transferring context: 34B                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/alpine:3.12.0@sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321                   1.2s
 => [internal] load build context                                                                                                                          0.0s
 => => transferring context: 217B                                                                                                                          0.0s
 => [ 1/10] FROM docker.io/library/alpine:3.12.0@sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321                                   0.0s
 => CACHED [ 2/10] RUN addgroup -S nginx     && adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx                                          0.0s
 => CACHED [ 3/10] RUN ["apk", "add", "--no-cache", "nginx", "nginx-mod-stream"]                                                                           0.0s
 => CACHED [ 4/10] RUN ln -sf /dev/stdout /var/log/nginx/access.log     && ln -sf /dev/stderr /var/log/nginx/error.log                                     0.0s
 => CACHED [ 5/10] RUN mkdir /app && mkdir /etc/nginx/tcpconf.d && chown -R nginx:nginx /etc/nginx                                                         0.0s
 => CACHED [ 6/10] ADD src/docker-startup.sh /app                                                                                                          0.0s
 => CACHED [ 7/10] ADD src/files/authorized_ip /etc/nginx/                                                                                                 0.0s
 => CACHED [ 8/10] ADD src/files/tcp.stream /etc/nginx/tcpconf.d                                                                                           0.0s
 => CACHED [ 9/10] COPY src/files/nginx_conf /etc/nginx/nginx.conf                                                                                         0.0s
 => CACHED [10/10] WORKDIR /app                                                                                                                            0.0s
 => exporting to image                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                    0.0s
 => => writing image sha256:eef64a82c04901437cfe394a4f3fe41f64948bb6131c137104aabe9a8f458027                                                               0.0s
 => => naming to docker.io/library/pay-tcp-proxy_pay-tcp-proxy                                                                                             0.0s
11:04 : GDS11088 : no_aws : (pp-8370-enable-nginx-stream-logging) : [~/gitdevel/github.com/alphagov/pay-tcp-proxy]
♥ $ docker-compose up
Creating network "pay-tcp-proxy_default" with the default driver
Creating pay-tcp-proxy_nginx-backend_1 ... done
Creating pay-tcp-proxy_pay-tcp-proxy_1 ... done
Attaching to pay-tcp-proxy_nginx-backend_1, pay-tcp-proxy_pay-tcp-proxy_1
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: using the "epoll" event method
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: nginx/1.21.1
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424)
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: OS: Linux 5.10.25-linuxkit
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: start worker processes
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: start worker process 7
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: start worker process 8
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: start worker process 9
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: start worker process 10
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: start worker process 11
nginx-backend_1  | 2021/07/26 10:05:00 [notice] 1#1: start worker process 12
```

And finally when accessing https://localhost the following lines are produced in the log:
```
pay-tcp-proxy_1  | 192.168.80.1 [26/Jul/2021:10:05:26 +0000] TCP 200 1321 526 0.028 "192.168.80.2:443" "526" "1321" "0.001"
pay-tcp-proxy_1  | 192.168.80.1 [26/Jul/2021:10:05:26 +0000] TCP 200 1321 526 0.027 "192.168.80.2:443" "526" "1321" "0.000"
nginx-backend_1  | 192.168.80.3 - - [26/Jul/2021:10:05:26 +0000] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
```

### CODE REVIEW

**Review by danworth — APPROVED** [review]
Looks great, the local testing docker-compose is a nice addition. I've run that and can see that the tcp stream logs come through in a similar format as the nginx http access logs, with the time in `[]` 👍

**Comment by danworth** [comment]
This is looking good so far, when running locally I can see original client IP being the docker network gateway
```
gds5062-2:pay-tcp-proxy danworth$ docker network inspect pay-tcp-proxy_default | jq 'try .[].IPAM.Config[].Gateway'
"172.20.0.1"
```
 being logged and inspecting the packets with `tcpdump -nXX -i any port 443` from the tcp-proxy container I can see the proxy protocol being sent (beings `PROXY.TCP4` in the ascii output

```
08:30:30.672231 IP 172.20.0.4.51724 > 172.20.0.3.443: Flags [P.], seq 1:45, ack 1, win 502, options [nop,nop,TS val 3666627359 ecr 981464133], length 44
        0x0000:  0000 0001 0006 0242 ac14 0004 0000 0800  .......B........
        0x0010:  4500 0060 eebb 4000 4006 f3ac ac14 0004  E..`..@.@.......
        0x0020:  ac14 0003 ca0c 01bb 25a9 de29 9c1f 283c  ........%..)..(<
        0x0030:  8018 01f6 5882 0000 0101 080a da8c 4b1f  ....X.........K.
        0x0040:  3a7f f445 5052 4f58 5920 5443 5034 2031  :..EPROXY.TCP4.1
        0x0050:  3732 2e32 302e 302e 3120 3137 322e 3230  72.20.0.1.172.20
        0x0060:  2e30 2e34 2035 3933 3836 2034 3433 0d0a  .0.4.59386.443..
```

**Comment by jfharden** [comment]
I've updated now to allow setting proxy protocol on or off based setting the env var `PROXY_PROTOCOL` to `on` or `off` (defaulting to off if no env var is provided.

Since the image will be deployed to both the new fargate infrastructure, and the old EC2 infrastructure we need to be able to control the setting in the short term. Once we have completely cut over to the fargate version we can remove the logic to disable proxy_protocol and return the container to a simpler state.

**Review by danworth — APPROVED** [review]
This looks great, follows existing patterns of using start up shell scripts to change nginx config based on environment variables.

**Comment by jfharden** [comment]
We have built and pushed this into ECR in test and tested it on the new fargate platform in test-12. Tomorrow morning we should:

1. Test it on the old fargate platform in test where PROXY_PROTOCOL is disabled
2. Merge this PR, allow the build to complete and to get a real build and release tag
3. Update test to use the real release tag
4. Remove all the temporary images we put into ECR in test
5. Deploy the following to staging and prod:
    a. Proxy protocol NLB change
    b. This docker image
    c. ECS Service definition to enable the PROXY_PROTOCOL env var

**Comment by jfharden** [comment]
Force push was after rebasing against origin/master to pull in the alpine base container update

**Comment by jfharden** [comment]
This (hopefully) final version of the container has been tested successfully in test-12.

**Review by katstevens — APPROVED** [review]
Thoroughly tested and well documented - love it.

**Pull request merged**
